apiVersion: apps.jfrog.com/v1alpha1
kind: SecretRotator
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.deploymentLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.deploymentLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  name: secretrotator-sample
spec: {{- include "common.tplvalues.render" (dict "value" .Values.secretRotatorSpec "context" $) | nindent 2 }}

